apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: blobreplicasets.raker22.com
spec:
  group: raker22.com
  version: v1alpha1
  names:
    kind: BlobReplicaSet
    plural: blobreplicasets
  scope: Namespaced